variables:
  CONTAINER_REGISTRY_URL: "neoplaygroundacr0.azurecr.io"
  CONTAINER_REGISTRY_USERNAME: $REGISTRY_USERNAME
  CONTAINER_REGISTRY_PASSWORD: $REGISTRY_PASSWORD
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_and_push_image:
  stage: build
  image: docker:19.03
  services:
    - docker:19.03-dind
  script:
    - docker login $CONTAINER_REGISTRY_URL -u $CONTAINER_REGISTRY_USERNAME -p $CONTAINER_REGISTRY_PASSWORD
    - docker build . -t $CONTAINER_REGISTRY_URL/keycloak:latest
    - docker push $CONTAINER_REGISTRY_URL/keycloak:latest
  tags:
    - azure-runner
  when: manual